### ISSUE TITLE
send direct message to user

### ISSUE THREAD

**Issue by fight-for-future-and-family** [sj14/review-bot#6]
hello, I just want to send direct message to user in mattermost via bot account ,so is it possible to achieve it ?
appreciate your response, thanks.

**Comment by sj14** [comment]
>**[Support SHIELD](https://gitlab.com/my_user/my_project/merge_requests/1940)**  
> 1 💬   3 👍  @hulk
>
>**[Ask Deadpool to join us](https://gitlab.com/my_user/my_project/merge_requests/1923)**  
> 3 💬   3 👍  @batman
>
>**[Repair the Helicarrier](https://gitlab.com/my_user/my_project/merge_requests/1777)**  
> 3 💬   @hulk @batman @groot @iron_man
>
>**[Find Kingpin](https://gitlab.com/my_user/my_project/merge_requests/1099)**  
> 2 💬   4 👍  You got all reviews, @daredevil.

Based on the example, it's currently not possible to send the `Support SHIELD` reminder directly to the user `hulk` or the `Repair the Helicarrier` reminder directly to the users `hulk`, `batman`, `groot` and `iron_man` using a 1:1 conversation.
You can only send the whole message with all the reminders to a channel (without @ prefix) or a single use (with @ prefix).

I hope this answers you question.
